### PR TITLE
Option: Automatically update TOC when I open a `.md` file

### PR DESCRIPTION
**Pull request by lanceplaine**
Close https://github.com/nok/markdown-toc/issues/83 thanks to @wyster

### CODE REVIEW

**Comment by lanceplaine** [comment]
@nok: Note that the option is OFF by default but you can decide to turn it ON by default :)

**Comment by lanceplaine** [comment]
@wyster: Looks like there are issues I didn't saw the first time:
  - Plugin keep running sometime (Cf. the video)
  - Have issues with the plugin `Markdown Preview` (it moves the preview, Cf. the video)

[video.zip](https://github.com/nok/markdown-toc/files/464630/video.zip)

**Comment by wyster** [comment]
@lanceplaine Without plugin all good?
Unfortunately I was not able to reproduce
Perhaps it makes sense to try this version https://github.com/wyster/markdown-toc/tree/feature/updateTocAfterSave?

**Comment by wyster** [comment]
From https://github.com/nok/markdown-toc/blob/master/README.md
> Refresh list on save with updateOnSave:1
It works... But, now this method call many time and it is initiated only after pressing ctrl + alt + c / r / u
I think we need to combine these settings, will update the list if enabled "Automatically update TOC" and updateOnSave:1, i changed my code

**Comment by lanceplaine** [comment]
@wyster: ok

I just tested your branch https://github.com/wyster/markdown-toc/tree/feature/updateTocAfterSave but for now it doesn't work (when I open a file and change a title it doesn't update the TOC). Are you currently working on this branch?

**Comment by wyster** [comment]
@lanceplaine I fixed this

**Comment by lanceplaine** [comment]
@wyster: I just tested your branch again and it seems to work :)

Do you want to do the PR on `nok/markdown-toc`? It would be better in case something else need to be fixed.

**Pull request closed without merging**
