### PR TITLE
add newline before <!-- /TOC --> for github/gitlab markdown parsing

### LINKED ISSUE #32: <!-- /TOC → appears on GitHub
Hello,

Is it a bug?

Thanks

screen shot 2015-06-25 at 8 49 05 pm

### PR DESCRIPTION
**Pull request by jonaswisplinghoff**
fixes #32

### CODE REVIEW

**Comment by n3dst4** [comment]
+1 for merging this as soon as it's convenient

**Comment by xolan** [comment]
+1 :)

**Comment by trumbitta** [comment]
:+1: :shipit:

**Comment by neersighted** [comment]
:+1:

**Pull request merged**
